### ISSUE TITLE
Capabilities - Need a way to request then

### ISSUE THREAD

**Issue by Skarsnik** [usb2snes/emulator-networkaccess#1]
A client need to be able to know what operation the emulator support.

We can probably just add a command to return the command supported. Or maybe group then.

**Comment by Skarsnik** [comment]
There is maybe 2-3 ways to go with this :
- Group of command, like controls commands, savestates commands, etc... The issue with this if we add a new command to one of the group and an emu does not support it, you don't know
- Add a simple command that list all supported command
- Add a simple command that allow to query if one command is supported, this look nice, but sound annoying to implement and use in the end

**Comment by black-sliver** [comment]
probably easiest to 
```
EMU_INFO
commands: comma,separated,list,of,supported,commands
```
and if an extension needs more than that, it could support
```EXTENSION_INFO```
and tell its features there.
in the absence of `commands` we can assume it implements all of [draft v2](https://github.com/usb2snes/emulator-networkaccess/blob/main/Protocol-Draft-v2.md), and remove from the list when an error is received

**Comment by black-sliver** [comment]
Added `commands` in commit 2c35cfd
